png("plot4.png", width=480, height=480)
par(mfcol = c(2,2))
plot(strptime(df$Datetime, "%d/%m/%Y %H:%M:%S"), df$Global_active_power, type="l", xlab="Global active Power (Kilowatts)", col = "black")
plot(strptime(df$Datetime, "%d/%m/%Y %H:%M:%S"), df$Sub_metering_1, type="l", xlab="",ylab="Energy sub metering", col = "black")
lines(strptime(df$Datetime, "%d/%m/%Y %H:%M:%S"), df$Sub_metering_2, type="l", xlab="",ylab="Energy sub metering", col = "red")
lines(strptime(df$Datetime, "%d/%m/%Y %H:%M:%S"), df$Sub_metering_3, type="l", xlab="",ylab="Energy sub metering", col = "blue")
legend("topright",lty=1, col=c("black", "red", "blue"), legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
plot(strptime(df$Datetime, "%d/%m/%Y %H:%M:%S"), df$Voltage, type="l", ylab="Voltage", col = "black")
plot(strptime(df$Datetime, "%d/%m/%Y %H:%M:%S"), df$Global_reactive_power, type="l", xlab = "datetime", ylab="Global_reactive_power", col = "black")
dev.off()